#include "stdafx.h"
#if defined(OS_WINDOWS)
#include <Windows.h>
#else
#include <stdarg.h>
#pragma GCC diagnostic ignored "-Wunused-parameter"
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"
#endif

#include "BS2EventStringUtil.h"
#include "Utility.h"
#include "BS_API.h"
#include "BS_Errno.h"


using namespace std;

string BS2EventStringUtil::getEventString(uint16_t eventCode)
{
	uint16_t mainEvent = eventCode & BS2_EVENT_MASK;
	uint16_t subEvent = eventCode & BS2_SUB_EVENT_MASK;

	string mainStr = getMainEventString(mainEvent);
	string subStr = getSubEventString(mainEvent, subEvent);

	//if (0 < mainEvent && 0 < subEvent)
	//{
	//	return getComplexEventString(eventCode);
	//}

	return (subStr.empty()) ? mainStr :  mainStr + " (" + subStr + ")";
}

string BS2EventStringUtil::getComplexEventString(uint16_t eventCode)
{
	switch (eventCode)
	{
	case BS2_EVENT_DEVICE_TIMEZONE_SET:						return "DEVICE_TIMEZONE_SET";
	case BS2_EVENT_DEVICE_DST_SET:							return "DEVICE_DST_SET";
	//case BS2_EVENT_DEVICE_ADMIN_LOGIN_FAIL:					return "DEVICE_ADMIN_LOGIN_FAIL";
	//case BS2_EVENT_DEVICE_ADMIN_LOGIN_FAIL_NOCREDENTIAL:	return "DEVICE_ADMIN_LOGIN_FAIL_NOCREDENTIAL";
	case BS2_EVENT_DEVICE_RTSP_CONNECTED:					return "DEVICE_RTSP_CONNECTED";
	case BS2_EVENT_DEVICE_RTSP_DISCONNECTED:				return "DEVICE_RTSP_DISCONNECTED";
	case BS2_EVENT_DEVICE_DATABASE_RESET:					return "DEVICE_DATABASE_RESET";
	case BS2_EVENT_DEVICE_FACTORY_RESET:					return "DEVICE_FACTORY_RESET";
	case BS2_EVENT_DEVICE_CONFIG_RESET_EX:					return "DEVICE_CONFIG_RESET_EX";
	case BS2_EVENT_DEVICE_FACTORY_RESET_WITHOUT_ETHERNET:	return "DEVICE_FACTORY_RESET_WITHOUT_ETHERNET";
	case BS2_EVENT_SIMULATED_EXIT_BUTTON:					return "SIMULATED_EXIT_BUTTON";
	//case BS2_EVENT_LICENSE_ENABLE_FAIL:						return "LICENSE_ENABLE_FAIL";
	//case BS2_EVENT_LICENSE_DISABLE_SUCCESS:					return "LICENSE_DISABLE_SUCCESS";
	//case BS2_EVENT_LICENSE_DISABLE_FAIL:					return "LICENSE_DISABLE_FAIL";
	//case BS2_EVENT_LICENSE_EXPIRED:							return "LICENSE_EXPIRED";
	//case BS2_EVENT_RELAY_ACTIVATE_REQUESTED_BY_OPERATOR:	return "RELAY_ACTIVATE_REQUESTED_BY_OPERATOR";
	//case BS2_EVENT_RELAY_DEACTIVATE_REQUESTED_BY_OPERATOR:	return "RELAY_DEACTIVATE_REQUESTED_BY_OPERATOR";
	//case BS2_EVENT_DOOR_OPEN_LOCKOVERRIDE_ALARM:			return "DOOR_OPEN_LOCKOVERRIDE_ALARM";
	//case BS2_EVENT_DOOR_OPEN_LOCKOVERRIDE_ALARM_CLEAR:		return "DOOR_OPEN_LOCKOVERRIDE_ALARM_CLEAR";
	//case BS2_EVENT_DOOR_LOCK_REQUEST_BY_SCHEDULE:			return "DOOR_LOCK_REQUEST_BY_SCHEDULE";
	//case BS2_EVENT_DOOR_LOCK_REQUEST_BY_FIRE_ALARM:			return "DOOR_LOCK_REQUEST_BY_FIRE_ALARM";
	//case BS2_EVENT_DOOR_LOCK_REQUEST_BY_OPERATOR:			return "DOOR_LOCK_REQUEST_BY_OPERATOR";
	//case BS2_EVENT_DOOR_UNLOCK_REQ_BY_SCHEDULE:				return "DOOR_UNLOCK_REQ_BY_SCHEDULE";
	//case BS2_EVENT_DOOR_UNLOCK_REQ_BY_FIRE_ALARM:			return "DOOR_UNLOCK_REQ_BY_FIRE_ALARM";
	//case BS2_EVENT_DOOR_UNLOCK_REQ_BY_OPERATOR:				return "DOOR_UNLOCK_REQ_BY_OPERATOR";
	//case BS2_EVENT_DOOR_UNLOCK_REQ_BY_LOCKOVERRIDE:			return "DOOR_UNLOCK_REQ_BY_LOCKOVERRIDE";
	//case BS2_EVENT_DOOR_SEND_UNLOCK:						return "DOOR_SEND_UNLOCK";
	//case BS2_EVENT_DOOR_SEND_LOCK:							return "DOOR_SEND_LOCK";
	//case BS2_EVENT_DOOR_SEND_RELEASE:						return "DOOR_SEND_RELEASE";
	//case BS2_EVENT_DOOR_FIRE_BUTTON_INPUT:					return "DOOR_FIRE_BUTTON_INPUT";
	//case BS2_EVENT_DOOR_FIRE_ALARM:							return "DOOR_FIRE_ALARM";
	//case BS2_EVENT_DOOR_FIRE_ALARM_CLEAR:					return "DOOR_FIRE_ALARM_CLEAR";
	//case BS2_EVENT_DOOR_NORMALIZED:							return "DOOR_NORMALIZED";
	}

	return "Unknown Complex Event";
}

string BS2EventStringUtil::getMainEventString(uint16_t mainEvent)
{
	switch (mainEvent) {
	case BS2_EVENT_VERIFY_SUCCESS: 					return "VERIFY_SUCCESS";
	case BS2_EVENT_VERIFY_FAIL: 					return "VERIFY_FAIL";
	case BS2_EVENT_VERIFY_DURESS: 					return "VERIFY_DURESS";
	case BS2_EVENT_IDENTIFY_SUCCESS: 				return "IDENTIFY_SUCCESS";
	case BS2_EVENT_IDENTIFY_FAIL: 					return "IDENTIFY_FAIL";
	case BS2_EVENT_IDENTIFY_DURESS: 				return "IDENTIFY_DURESS";
	case BS2_EVENT_DUAL_AUTH_SUCCESS: 				return "DUAL_AUTH_SUCCESS";
	case BS2_EVENT_DUAL_AUTH_FAIL: 					return "DUAL_AUTH_FAIL";
	case BS2_EVENT_AUTH_FAILED: 					return "AUTH_FAILED";
	case BS2_EVENT_ACCESS_DENIED: 					return "ACCESS_DENIED";
	case BS2_EVENT_FAKE_FINGER_DETECTED: 			return "FAKE_FINGER_DETECTED";
	case BS2_EVENT_BYPASS_SUCCESS: 					return "BYPASS_SUCCESS";
	case BS2_EVENT_BYPASS_FAIL: 					return "BYPASS_FAIL";
	case BS2_EVENT_ABNORMAL_TEMPERATURE_DETECTED: 	return "ABNORMAL_TEMPERATURE_DETECTED";
	case BS2_EVENT_UNMASKED_FACE_DETECTED: 			return "UNMASKED_FACE_DETECTED";

	case BS2_EVENT_USER_ENROLL_SUCCESS: 			return "USER_ENROLL_SUCCESS";
	case BS2_EVENT_USER_ENROLL_FAIL: 				return "USER_ENROLL_FAIL";
	case BS2_EVENT_USER_UPDATE_SUCCESS: 			return "USER_UPDATE_SUCCESS";
	case BS2_EVENT_USER_DELETE_SUCCESS: 			return "USER_DELETE_SUCCESS";
	case BS2_EVENT_USER_UPDATE_FAIL:				return "USER_UPDATE_FAIL";
	case BS2_EVENT_USER_DELETE_FAIL:				return "USER_DELETE_FAIL";
	case BS2_EVENT_USER_DELETE_ALL_SUCCESS:			return "USER_DELETE_ALL_SUCCESS";
	case BS2_EVENT_USER_ISSUE_AOC_SUCCESS:			return "USER_ISSUE_AOC_SUCCESS";
	case BS2_EVENT_USER_DUPLICATE_CREDENTIAL:		return "USER_DUPLICATE_CREDENTIAL";
	case BS2_EVENT_USER_UPDATE_PARTIAL_SUCCESS:		return "USER_UPDATE_PARTIAL_SUCCESS";
	case BS2_EVENT_USER_UPDATE_PARTIAL_FAIL:		return "USER_UPDATE_PARTIAL_FAIL";
	case BS2_EVENT_USER_RELOADED:					return "USER_RELOADED";

	case BS2_EVENT_DEVICE_SYSTEM_RESET:				return "DEVICE_SYSTEM_RESET";
	case BS2_EVENT_DEVICE_SYSTEM_ERROR_OPENGL:		return "DEVICE_SYSTEM_ERROR_OPENGL";
	case BS2_EVENT_DEVICE_SYSTEM_STARTED:			return "DEVICE_SYSTEM_STARTED";
	case BS2_EVENT_DEVICE_TIME_SET:					return "DEVICE_TIME_SET";
	case BS2_EVENT_DEVICE_LINK_CONNECTED:			return "DEVICE_LINK_CONNECTED";
	case BS2_EVENT_DEVICE_LINK_DISCONNETED:			return "DEVICE_LINK_DISCONNETED";
	case BS2_EVENT_DEVICE_DHCP_SUCCESS:				return "DEVICE_DHCP_SUCCESS";
	case BS2_EVENT_DEVICE_ADMIN_MENU:				return "DEVICE_ADMIN_MENU";
	case BS2_EVENT_DEVICE_UI_LOCKED:				return "DEVICE_UI_LOCKED";
	case BS2_EVENT_DEVICE_UI_UNLOCKED:				return "DEVICE_UI_UNLOCKED";
	case BS2_EVENT_DEVICE_COMM_LOCKED:				return "DEVICE_COMM_LOCKED";
	case BS2_EVENT_DEVICE_COMM_UNLOCKED:			return "DEVICE_COMM_UNLOCKED";
	case BS2_EVENT_DEVICE_TCP_CONNECTED:			return "DEVICE_TCP_CONNECTED";
	case BS2_EVENT_DEVICE_TCP_DISCONNECTED:			return "DEVICE_TCP_DISCONNECTED";
	case BS2_EVENT_DEVICE_RS485_CONNECTED:			return "DEVICE_RS485_CONNECTED";
	case BS2_EVENT_DEVICE_RS485_DISCONNCTED:		return "DEVICE_RS485_DISCONNCTED";
	//case BS2_EVENT_DEVICE_IO_DETECTED:				return "DEVICE_IO_DETECTED";

	case BS2_EVENT_DEVICE_TAMPER_ON:				return "DEVICE_TAMPER_ON";
	case BS2_EVENT_DEVICE_TAMPER_OFF:				return "DEVICE_TAMPER_OFF";
	case BS2_EVENT_DEVICE_EVENT_LOG_CLEARED:		return "DEVICE_EVENT_LOG_CLEARED";
	case BS2_EVENT_DEVICE_FIRMWARE_UPGRADED:		return "DEVICE_FIRMWARE_UPGRADED";
	case BS2_EVENT_DEVICE_RESOURCE_UPGRADED:		return "DEVICE_RESOURCE_UPGRADED";
	case BS2_EVENT_DEVICE_CONFIG_RESET:				return "DEVICE_CONFIG_RESET";
	case BS2_EVENT_SUPERVISED_INPUT_SHORT:			return "SUPERVISED_INPUT_SHORT";
	case BS2_EVENT_SUPERVISED_INPUT_OPEN:			return "SUPERVISED_INPUT_OPEN";
	case BS2_EVENT_DEVICE_AC_FAIL:					return "DEVICE_AC_FAIL";
	case BS2_EVENT_DEVICE_AC_SUCCESS:				return "DEVICE_AC_SUCCESS";
	case BS2_EVENT_EXIT_BUTTON:						return "EXIT_BUTTON";
	case BS2_EVENT_OPERATOR_OPEN:					return "OPERATOR_OPEN";
	case BS2_EVENT_VOIP_OPEN:						return "VOIP_OPEN";
	//case BS2_EVENT_LICENSE_ENABLE_SUCCESS:			return "LICENSE_ENABLE_SUCCESS";
	//case BS2_EVENT_UZ_BATTERY_LV_CHANGE:			return "UZ_BATTERY_LV_CHANGE";

	case BS2_EVENT_DOOR_UNLOCKED:					return "DOOR_UNLOCKED";
	case BS2_EVENT_DOOR_LOCKED:						return "DOOR_LOCKED";
	case BS2_EVENT_DOOR_OPENED:						return "DOOR_OPENED";
	case BS2_EVENT_DOOR_CLOSED:						return "DOOR_CLOSED";
	case BS2_EVENT_DOOR_FORCED_OPEN:				return "DOOR_FORCED_OPEN";
	case BS2_EVENT_DOOR_HELD_OPEN:					return "DOOR_HELD_OPEN";
	case BS2_EVENT_DOOR_FORCED_OPEN_ALARM:			return "DOOR_FORCED_OPEN_ALARM";
	case BS2_EVENT_DOOR_FORCED_OPEN_ALARM_CLEAR:	return "DOOR_FORCED_OPEN_ALARM_CLEAR";
	case BS2_EVENT_DOOR_HELD_OPEN_ALARM:			return "DOOR_HELD_OPEN_ALARM";
	case BS2_EVENT_DOOR_HELD_OPEN_ALARM_CLEAR:		return "DOOR_HELD_OPEN_ALARM_CLEAR";
	case BS2_EVENT_DOOR_APB_ALARM:					return "DOOR_APB_ALARM";
	case BS2_EVENT_DOOR_APB_ALARM_CLEAR:			return "DOOR_APB_ALARM_CLEAR";
	case BS2_EVENT_DOOR_RELEASE:					return "DOOR_RELEASE";
	case BS2_EVENT_DOOR_LOCK:						return "DOOR_LOCK";
	case BS2_EVENT_DOOR_UNLOCK:						return "DOOR_UNLOCK";
	//case BS2_EVENT_DOOR_SEND_UNLOCK_TIMER:			return "DOOR_SEND_UNLOCK_TIMER";

	case BS2_EVENT_ZONE_APB_VIOLATION:				return "ZONE_APB_VIOLATION";
	case BS2_EVENT_ZONE_APB_ALARM:					return "ZONE_APB_ALARM";
	case BS2_EVENT_ZONE_APB_ALARM_CLEAR:			return "ZONE_APB_ALARM_CLEAR";
	case BS2_EVENT_ZONE_TIMED_APB_VIOLATION:		return "ZONE_TIMED_APB_VIOLATION";
	case BS2_EVENT_ZONE_TIMED_APB_ALARM:			return "ZONE_TIMED_APB_ALARM";
	case BS2_EVENT_ZONE_TIMED_APB_ALARM_CLEAR:		return "ZONE_TIMED_APB_ALARM_CLEAR";
	case BS2_EVENT_ZONE_FIRE_ALARM_INPUT:			return "ZONE_FIRE_ALARM_INPUT";
	case BS2_EVENT_ZONE_FIRE_ALARM:					return "ZONE_FIRE_ALARM";
	case BS2_EVENT_ZONE_FIRE_ALARM_CLEAR:			return "ZONE_FIRE_ALARM_CLEAR";
	case BS2_EVENT_ZONE_SCHEDULED_LOCK_VIOLATION:	return "ZONE_SCHEDULED_LOCK_VIOLATION";
	case BS2_EVENT_ZONE_SCHEDULED_LOCK_START:		return "ZONE_SCHEDULED_LOCK_START";
	case BS2_EVENT_ZONE_SCHEDULED_LOCK_END:			return "ZONE_SCHEDULED_LOCK_END";
	case BS2_EVENT_ZONE_SCHEDULED_UNLOCK_START:		return "ZONE_SCHEDULED_UNLOCK_START";
	case BS2_EVENT_ZONE_SCHEDULED_UNLOCK_END:		return "ZONE_SCHEDULED_UNLOCK_END";
	case BS2_EVENT_ZONE_SCHEDULED_LOCK_ALARM:		return "ZONE_SCHEDULED_LOCK_ALARM";
	case BS2_EVENT_ZONE_SCHEDULED_LOCK_ALARM_CLEAR:	return "ZONE_SCHEDULED_LOCK_ALARM_CLEAR";
	
	case BS2_EVENT_FLOOR_ACTIVATED:					return "FLOOR_ACTIVATED";
	case BS2_EVENT_FLOOR_DEACTIVATED:				return "FLOOR_DEACTIVATED";
	case BS2_EVENT_FLOOR_RELEASE:					return "FLOOR_RELEASE";
	case BS2_EVENT_FLOOR_ACTIVATE:					return "FLOOR_ACTIVATE";
	case BS2_EVENT_FLOOR_DEACTIVATE:				return "FLOOR_DEACTIVATE";
	case BS2_EVENT_LIFT_ALARM_INPUT:				return "LIFT_ALARM_INPUT";
	case BS2_EVENT_LIFT_ALARM:						return "LIFT_ALARM";
	case BS2_EVENT_LIFT_ALARM_CLEAR:				return "LIFT_ALARM_CLEAR";
	case BS2_EVENT_ALL_FLOOR_ACTIVATED:				return "ALL_FLOOR_ACTIVATED";
	case BS2_EVENT_ALL_FLOOR_DEACTIVATED:			return "ALL_FLOOR_DEACTIVATED";

	case BS2_EVENT_GLOBAL_APB_EXCUSED:						return "GLOBAL_APB_EXCUSED";
	case BS2_EVENT_DEVICE_ZONE_ENTRANCE_LIMIT_VIOLATION:	return "DEVICE_ZONE_ENTRANCE_LIMIT_VIOLATION";
	case BS2_EVENT_DEVICE_ZONE_ENTRANCE_LIMIT_ALARM:		return "DEVICE_ZONE_ENTRANCE_LIMIT_ALARM";
	case BS2_EVENT_DEVICE_ZONE_ENTRANCE_LIMIT_ALARM_CLEAR:	return "DEVICE_ZONE_ENTRANCE_LIMIT_ALARM_CLEAR";

	case BS2_EVENT_ZONE_INTRUSION_ALARM_VIOLATION:			return "INTRUSION_ALARM_VIOLATION";
	case BS2_EVENT_ZONE_INTRUSION_ALARM_ARM_GRANTED:		return "INTRUSION_ALARM_ARM_GRANTED";
	case BS2_EVENT_ZONE_INTRUSION_ALARM_ARM_SUCCESS:		return "INTRUSION_ALARM_ARM_SUCCESS";
	case BS2_EVENT_ZONE_INTRUSION_ALARM_ARM_FAIL:			return "INTRUSION_ALARM_ARM_FAIL";
	case BS2_EVENT_ZONE_INTRUSION_ALARM_DISARM_GRANTED:		return "INTRUSION_ALARM_DISARM_GRANTED";
	case BS2_EVENT_ZONE_INTRUSION_ALARM_DISARM_SUCCESS:		return "INTRUSION_ALARM_DISARM_SUCCESS";
	case BS2_EVENT_ZONE_INTRUSION_ALARM_DISARM_FAIL:		return "INTRUSION_ALARM_DISARM_FAIL";
	case BS2_EVENT_ZONE_INTRUSION_ALARM:					return "INTRUSION_ALARM";
	case BS2_EVENT_ZONE_INTRUSION_ALARM_CLEAR:				return "INTRUSION_ALARM_CLEAR";
	case BS2_EVENT_ZONE_INTRUSION_ALARM_ARM_DENIED:			return "INTRUSION_ALARM_ARM_DENIED";
	case BS2_EVENT_ZONE_INTRUSION_ALARM_DISARM_DENIED:		return "INTRUSION_ALARM_DISARM_DENIED";

	case BS2_EVENT_ZONE_INTERLOCK_VIOLATION:				return "INTERLOCK_VIOLATION";
	case BS2_EVENT_ZONE_INTERLOCK_ALARM:					return "INTERLOCK_ALARM";
	case BS2_EVENT_ZONE_INTERLOCK_ALARM_DOOR_OPEN_DENIED:	return "INTERLOCK_ALARM_DOOR_OPEN_DENIED";
	case BS2_EVENT_ZONE_INTERLOCK_ALARM_INDOOR_DENIED:		return "INTERLOCK_ALARM_INDOOR_DENIED";
	case BS2_EVENT_ZONE_INTERLOCK_ALARM_CLEAR:				return "INTERLOCK_ALARM_CLEAR";
	case BS2_EVENT_ZONE_AUTH_LIMIT_VIOLATION:				return "AUTH_LIMIT_VIOLATION";
	case BS2_EVENT_GLOBAL_AUTH_LIMIT_EXCUSED:				return "GLOBAL_AUTH_LIMIT_EXCUSED";

	case BS2_EVENT_ZONE_MUSTER_VIOLATION:					return "MUSTER_VIOLATION";
	case BS2_EVENT_ZONE_MUSTER_ALARM:						return "MUSTER_ALARM";
	case BS2_EVENT_ZONE_MUSTER_ALARM_CLEAR:					return "MUSTER_ALARM_CLEAR";

	case BS2_EVENT_ZONE_LIFT_LOCK_VIOLATION:				return "LIFT_LOCK_VIOLATION";
	case BS2_EVENT_ZONE_LIFT_LOCK_START:					return "LIFT_LOCK_START";
	case BS2_EVENT_ZONE_LIFT_LOCK_END:						return "LIFT_LOCK_END";
	case BS2_EVENT_ZONE_LIFT_UNLOCK_START:					return "LIFT_UNLOCK_START";
	case BS2_EVENT_ZONE_LIFT_UNLOCK_END:					return "LIFT_UNLOCK_END";
	case BS2_EVENT_ZONE_LIFT_LOCK_ALARM:					return "LIFT_LOCK_ALARM";
	case BS2_EVENT_ZONE_LIFT_LOCK_ALARM_CLEAR:				return "LIFT_LOCK_ALARM_CLEAR";

	case BS2_EVENT_DEVICE_USER_SYNC_TO_SERVER_FAIL:			return "DEVICE_USER_SYNC_TO_SERVER_FAIL";
	case BS2_EVENT_BREAK_GLASS:								return "BREAK_GLASS";
	case BS2_EVENT_MEMORY_FULL_MIGRATION:					return "MEMORY_FULL_MIGRATION";
	case BS2_EVENT_RELAY_ACTION_ON:							return "RELAY_ACTION_ON";
	case BS2_EVENT_RELAY_ACTION_OFF:						return "RELAY_ACTION_OFF";
	case BS2_EVENT_RELAY_ACTION_KEEP:						return "RELAY_ACTION_KEEP";
	}

	char buf[32] = {};
	sprintf(buf, "Unknown(0x%04X)", mainEvent);
	return string(buf);
}

string BS2EventStringUtil::getSubEventString(uint16_t mainEvent, uint16_t subEvent)
{
	if (subEvent == 0)
		return "";

	switch (mainEvent)
	{
	case BS2_EVENT_VERIFY_SUCCESS:
	case BS2_EVENT_VERIFY_DURESS:
		return getSubEventStringVerify(subEvent);
	
	case BS2_EVENT_VERIFY_FAIL:
	case BS2_EVENT_IDENTIFY_FAIL:
		return getSubEventStringVerifyFail(subEvent);

	case BS2_EVENT_IDENTIFY_SUCCESS:
	case BS2_EVENT_IDENTIFY_DURESS:
		return getSubEventStringIdentify(subEvent);

	case BS2_EVENT_DUAL_AUTH_FAIL:
		return getSubEventStringDualAuthFail(subEvent);

	case BS2_EVENT_AUTH_FAILED:
		return getSubEventStringAuthFail(subEvent);

	case BS2_EVENT_ACCESS_DENIED:
		return getSubEventStringAccessDenied(subEvent);

	case BS2_EVENT_BYPASS_FAIL:
		return getSubEventStringBypassFail(subEvent);

	case BS2_EVENT_ABNORMAL_TEMPERATURE_DETECTED:
		return getSubEventStringAbnormalTemperature(subEvent);

	case BS2_EVENT_UNMASKED_FACE_DETECTED:
		return getSubEventStringUnmaskedFace(subEvent);

	case BS2_EVENT_USER_ENROLL_SUCCESS:
	case BS2_EVENT_USER_UPDATE_SUCCESS:
	case BS2_EVENT_USER_DELETE_SUCCESS:
	case BS2_EVENT_USER_DELETE_ALL_SUCCESS:
		return getSubEventStringUserEnroll(subEvent);

	case BS2_EVENT_USER_ENROLL_FAIL:
		return getSubEventStringUserEnrollFail(subEvent);
	
	case BS2_EVENT_USER_UPDATE_FAIL:
		return getSubEventStringUserUpdateFail(subEvent);

	case BS2_EVENT_DOOR_RELEASE:
		return getSubEventStringDoor(subEvent);
		
	case BS2_EVENT_FLOOR_RELEASE:
	case BS2_EVENT_FLOOR_ACTIVATE:
	case BS2_EVENT_FLOOR_DEACTIVATE:
		return getSubEventStringFloor(subEvent);

	case BS2_EVENT_ZONE_APB_VIOLATION:
	case BS2_EVENT_ZONE_TIMED_APB_VIOLATION:
		return getSubEventStringAPBZone(subEvent);

	case BS2_EVENT_DEVICE_ZONE_ENTRANCE_LIMIT_VIOLATION:
		return getSubEventStringEntranceLimitZone(subEvent);

	case BS2_EVENT_ZONE_INTERLOCK_VIOLATION:
		return getSubEventStringInterlockZone(subEvent);

	case BS2_EVENT_ZONE_AUTH_LIMIT_VIOLATION:
		return getSubEventStringAuthLimitZone(subEvent);

	//case BS2_EVENT_DEVICE_IO_DETECTED:
	//	return getSubEventStringDeviceIO(subEvent);

	default:
		break;
	}

	char buf[32];
	sprintf(buf, "Sub:0x%02X", subEvent);
	return string(buf);
}

string BS2EventStringUtil::getSubEventStringVerify(uint16_t subEvent)
{
	switch (subEvent)
	{
	case BS2_SUB_EVENT_VERIFY_ID_PIN:				return "ID_PIN";
	case BS2_SUB_EVENT_VERIFY_ID_FINGER:			return "ID_FINGER";
	case BS2_SUB_EVENT_VERIFY_ID_FINGER_PIN:		return "ID_FINGER_PIN";
	case BS2_SUB_EVENT_VERIFY_ID_FACE:				return "ID_FACE";
	case BS2_SUB_EVENT_VERIFY_ID_FACE_PIN:			return "ID_FACE_PIN";
	case BS2_SUB_EVENT_VERIFY_CARD:					return "CARD";
	case BS2_SUB_EVENT_VERIFY_CARD_PIN:				return "CARD_PIN";
	case BS2_SUB_EVENT_VERIFY_CARD_FINGER:			return "CARD_FINGER";
	case BS2_SUB_EVENT_VERIFY_CARD_FINGER_PIN:		return "CARD_FINGER_PIN";
	case BS2_SUB_EVENT_VERIFY_CARD_FACE:			return "CARD_FACE";
	case BS2_SUB_EVENT_VERIFY_CARD_FACE_PIN:		return "CARD_FACE_PIN";
	case BS2_SUB_EVENT_VERIFY_AOC:					return "AOC";
	case BS2_SUB_EVENT_VERIFY_AOC_PIN:				return "AOC_PIN";
	case BS2_SUB_EVENT_VERIFY_AOC_FINGER:			return "AOC_FINGER";
	case BS2_SUB_EVENT_VERIFY_AOC_FINGER_PIN:		return "AOC_FINGER_PIN";
	case BS2_SUB_EVENT_VERIFY_CARD_FACE_FINGER:		return "CARD_FACE_FINGER";
	case BS2_SUB_EVENT_VERIFY_CARD_FINGER_FACE:		return "CARD_FINGER_FACE";
	case BS2_SUB_EVENT_VERIFY_ID_FACE_FINGER:		return "ID_FACE_FINGER";
	case BS2_SUB_EVENT_VERIFY_ID_FINGER_FACE:		return "ID_FINGER_FACE";
	case BS2_SUB_EVENT_VERIFY_QR:					return "QR";
	case BS2_SUB_EVENT_VERIFY_QR_PIN:				return "QR_PIN";
	case BS2_SUB_EVENT_VERIFY_QR_FINGER:			return "QR_FINGER";
	case BS2_SUB_EVENT_VERIFY_QR_FINGER_PIN:		return "QR_FINGER_PIN";
	case BS2_SUB_EVENT_VERIFY_QR_FACE:				return "QR_FACE";
	case BS2_SUB_EVENT_VERIFY_QR_FACE_PIN:			return "QR_FACE_PIN";
	case BS2_SUB_EVENT_VERIFY_QR_FACE_FINGER:		return "QR_FACE_FINGER";
	case BS2_SUB_EVENT_VERIFY_QR_FINGER_FACE:		return "QR_FINGER_FACE";
	//case BS2_SUB_EVENT_VERIFY_LOCKOVERRIDE:			return "LOCKOVERRIDE";
	}

	return "";
}

string BS2EventStringUtil::getSubEventStringVerifyFail(uint16_t subEvent)
{
	switch (subEvent)
	{
	case BS2_SUB_EVENT_CREDENTIAL_ID:				return "ID";
	case BS2_SUB_EVENT_CREDENTIAL_CARD:				return "CARD";
	case BS2_SUB_EVENT_CREDENTIAL_PIN:				return "PIN";
	case BS2_SUB_EVENT_CREDENTIAL_FINGER:			return "FINGER";
	case BS2_SUB_EVENT_CREDENTIAL_FACE:				return "FACE";
	case BS2_SUB_EVENT_CREDENTIAL_AOC_PIN:			return "AOC_PIN";
	case BS2_SUB_EVENT_CREDENTIAL_AOC_FINGER:		return "AOC_FINGER";
	case BS2_SUB_EVENT_CREDENTIAL_MOBILE_CARD:		return "MOBILE_CARD";
	case BS2_SUB_EVENT_CREDENTIAL_QR:				return "QR";
	//case BS2_SUB_EVENT_CREDENTIAL_ACCESS_PIN:		return "ACCESS_PIN";
	case BS2_SUB_EVENT_NON_NUMERIC_QR:				return "NON_NUMERIC_QR";
	case BS2_SUB_EVENT_NON_PRINTABLE_QR:			return "NON_PRINTABLE_QR";
	case BS2_SUB_EVENT_TOO_LONG_QR:					return "TOO_LONG_QR";
	}

	return "";
}

string BS2EventStringUtil::getSubEventStringIdentify(uint16_t subEvent)
{
	switch (subEvent)
	{
	case BS2_SUB_EVENT_IDENTIFY_FINGER:				return "FINGER";
	case BS2_SUB_EVENT_IDENTIFY_FINGER_PIN:			return "FINGER_PIN";
	case BS2_SUB_EVENT_IDENTIFY_FACE:				return "FACE";
	case BS2_SUB_EVENT_IDENTIFY_FACE_PIN:			return "FACE_PIN";
	case BS2_SUB_EVENT_IDENTIFY_FACE_FINGER:		return "FACE_FINGER";
	case BS2_SUB_EVENT_IDENTIFY_FACE_FINGER_PIN:	return "FACE_FINGER_PIN";
	case BS2_SUB_EVENT_IDENTIFY_FINGER_FACE:		return "FINGER_FACE";
	case BS2_SUB_EVENT_IDENTIFY_FINGER_FACE_PIN:	return "FINGER_FACE_PIN";
	}

	return "";
}

string BS2EventStringUtil::getSubEventStringDualAuthFail(uint16_t subEvent)
{
	switch (subEvent)
	{
	case BS2_SUB_EVENT_DUAL_AUTH_FAIL_TIMEOUT:		return "TIMEOUT";
	case BS2_SUB_EVENT_DUAL_AUTH_FAIL_ACCESS_GROUP:	return "ACCESS_GROUP";
	}

	return "";
}

string BS2EventStringUtil::getSubEventStringAuthFail(uint16_t subEvent)
{
	switch (subEvent)
	{
	case BS2_SUB_EVENT_AUTH_FAIL_INVALID_AUTH_MODE:		return "INVALID_AUTH_MODE";
	case BS2_SUB_EVENT_AUTH_FAIL_INVALID_CREDENTIAL:	return "INVALID_CREDENTIAL";
	case BS2_SUB_EVENT_AUTH_FAIL_TIMEOUT:				return "TIMEOUT";
	case BS2_SUB_EVENT_AUTH_FAIL_MATCHING_REFUSAL:		return "MATCHING_REFUSAL";
	//case BS2_SUB_EVENT_AUTH_FAIL_DOOR_LOCKED:			return "DOOR_LOCKED";
	}

	return "";
}

string BS2EventStringUtil::getSubEventStringAccessDenied(uint16_t subEvent)
{
	switch (subEvent)
	{
	case BS2_SUB_EVENT_ACCESS_DENIED_ACCESS_GROUP:			return "ACCESS_GROUP";
	case BS2_SUB_EVENT_ACCESS_DENIED_DISABLED:				return "DISABLED";
	case BS2_SUB_EVENT_ACCESS_DENIED_EXPIRED:				return "EXPIRED";
	case BS2_SUB_EVENT_ACCESS_DENIED_ON_BLACKLIST:			return "ON_BLACKLIST";
	case BS2_SUB_EVENT_ACCESS_DENIED_APB:					return "ANTIPASSBACK";
	case BS2_SUB_EVENT_ACCESS_DENIED_TIMED_APB:				return "TIMED_ANTIPASSBACK";
	case BS2_SUB_EVENT_ACCESS_DENIED_SCHEDULED_LOCK:		return "SCHEDULED_LOCK";
	case BS2_SUB_EVENT_ACCESS_EXCUSED_APB:					return "EXCUSED_ANTIPASSBACK";
	case BS2_SUB_EVENT_ACCESS_EXCUSED_TIMED_APB:			return "EXCUSED_TIMED_ANTIPASSBACK";
	case BS2_SUB_EVENT_ACCESS_DENIED_FACE_DETECTION:		return "FACE_DETECTION";
	case BS2_SUB_EVENT_ACCESS_DENIED_CAMERA_CAPTURE:		return "CAMERA_CAPTURE";
	case BS2_SUB_EVENT_ACCESS_DENIED_FAKE_FINGER:			return "FAKE_FINGER";
	case BS2_SUB_EVENT_ACCESS_DENIED_DEVICE_ZONE_ENTRANCE_LIMIT:	return "DEVICE_ZONE_ENTRANCE_LIMIT";
	case BS2_SUB_EVENT_ACCESS_DENIED_INTRUSION_ALARM:		return "INTRUSION_ALARM";
	case BS2_SUB_EVENT_ACCESS_DENIED_INTERLOCK:				return "INTERLOCK";
	case BS2_SUB_EVENT_ACCESS_EXCUSED_AUTH_LIMIT:			return "EXCUSED_AUTH_LIMIT";
	case BS2_SUB_EVENT_ACCESS_DENIED_AUTH_LIMIT:			return "AUTH_LIMIT";
	case BS2_SUB_EVENT_ACCESS_DENIED_ANTI_TAILGATE:			return "ANTI_TAILGATE";
	case BS2_SUB_EVENT_ACCESS_DENIED_HIGH_TEMPERATURE:		return "HIGH_TEMPERATURE";
	case BS2_SUB_EVENT_ACCESS_DENIED_NO_TEMPERATURE:		return "NO_TEMPERATURE";
	case BS2_SUB_EVENT_ACCESS_DENIED_UNMASKED_FACE:			return "UNMASKED_FACE";
	//case BS2_SUB_EVENT_ACCESS_DENIED_OCCUPANCY_LIMIT:		return "OCCUPANCY_LIMIT";
	//case BS2_SUB_EVENT_ACCESS_DENIED_DOOR_LOCKED:			return "DOOR_LOCKED";
	//case BS2_SUB_EVENT_ACCESS_DENIED_DISABLED_ACCESS_GROUP:	return "DISABLED_ACCESS_GROUP";
	//case BS2_SUB_EVENT_ACCESS_DENIED_DISABLED_ACCESS_LEVEL:	return "DISABLED_ACCESS_LEVEL";
	//case BS2_SUB_EVENT_ACCESS_DENIED_DISABLED_FLOOR_LEVEL:	return "DISABLED_FLOOR_LEVEL";
	}

	return "";
}

string BS2EventStringUtil::getSubEventStringBypassFail(uint16_t subEvent)
{
	switch (subEvent)
	{
	case BS2_SUB_EVENT_BYPASS_NO_VIOLATION:					return "NO_VIOLATION";
	case BS2_SUB_EVENT_BYPASS_THERMAL_VIOLATION:			return "THERMAL_VIOLATION";
	case BS2_SUB_EVENT_BYPASS_MASK_VIOLATION:				return "MASK_VIOLATION";
	case BS2_SUB_EVENT_BYPASS_MASK_THERMAL_VIOLATION:		return "MASK_THERMAL_VIOLATION";
	}

	return "";
}

string BS2EventStringUtil::getSubEventStringAbnormalTemperature(uint16_t subEvent)
{
	switch (subEvent)
	{
	case BS2_SUB_EVENT_HIGH_TEMPERATURE:					return "HIGH_TEMPERATURE";
	case BS2_SUB_EVENT_NO_TEMPERATURE:						return "NO_TEMPERATURE";
	}

	return "";
}

string BS2EventStringUtil::getSubEventStringUnmaskedFace(uint16_t subEvent)
{
	switch (subEvent)
	{
	case BS2_SUB_EVENT_UNMASKED_FACE:		return "UNMASKED_FACE";
	}

	return "";
}


string BS2EventStringUtil::getSubEventStringUserEnroll(uint16_t subEvent)
{
	switch (subEvent)
	{
	case 0x01:			return "BY SERVER";
	case 0x02:			return "BY DEVICE";
	}

	return "";
}

string BS2EventStringUtil::getSubEventStringUserEnrollFail(uint16_t subEvent)
{
	switch (subEvent)
	{
	case BS2_SUB_EVENT_ENROLL_FAIL_INVALID_FACE:			return "INVALID_FACE";
	case BS2_SUB_EVENT_ENROLL_FAIL_MISMATCHED_FORMAT:		return "MISMATCHED_FORMAT";
	case BS2_SUB_EVENT_ENROLL_FAIL_FULL_CREDENTIAL:			return "FULL_CREDENTIAL";
	case BS2_SUB_EVENT_ENROLL_FAIL_INVALID_USER:			return "INVALID_USER";
	case BS2_SUB_EVENT_ENROLL_FAIL_INTERNAL_ERROR:			return "INTERNAL_ERROR";
	}

	return "";
}

string BS2EventStringUtil::getSubEventStringUserUpdateFail(uint16_t subEvent)
{
	switch (subEvent)
	{
	case BS2_SUB_EVENT_UPDATE_FAIL_INVALID_FACE:			return "INVALID_FACE";
	case BS2_SUB_EVENT_UPDATE_FAIL_MISMATCHED_FORMAT:		return "MISMATCHED_FORMAT";
	case BS2_SUB_EVENT_UPDATE_FAIL_FULL_CREDENTIAL:			return "FULL_CREDENTIAL";
	case BS2_SUB_EVENT_UPDATE_FAIL_INVALID_USER:			return "INVALID_USER";
	case BS2_SUB_EVENT_UPDATE_FAIL_INTERNAL_ERROR:			return "INTERNAL_ERROR";
	}

	return "";
}

string BS2EventStringUtil::getSubEventStringDoor(uint16_t subEvent)
{
	switch (subEvent)
	{
	case BS2_SUB_EVENT_DOOR_FLAG_SCHEDULE:					return "SCHEDULE";
	case BS2_SUB_EVENT_DOOR_FLAG_OPERATOR:					return "OPERATOR";
	case BS2_SUB_EVENT_DOOR_FLAG_EMERGENCY:					return "EMERGENCY";
	//case BS2_SUB_EVENT_DOOR_FLAG_LOCKOVERRIDE:				return "LOCKOVERRIDE";
	}

	return "";
}

string BS2EventStringUtil::getSubEventStringFloor(uint16_t subEvent)
{
	switch (subEvent)
	{
	case BS2_SUB_EVENT_FLOOR_FLAG_SCHEDULE:					return "SCHEDULE";
	case BS2_SUB_EVENT_FLOOR_FLAG_OPERATOR:					return "OPERATOR";
	case BS2_SUB_EVENT_FLOOR_FLAG_ACTION:					return "ACTION";
	case BS2_SUB_EVENT_FLOOR_FLAG_EMERGENCY:				return "EMERGENCY";
	}

	return "";
}

string BS2EventStringUtil::getSubEventStringAPBZone(uint16_t subEvent)
{
	switch (subEvent)
	{
	case BS2_SUB_EVENT_ZONE_HARD_APB:						return "HARD_APB";
	case BS2_SUB_EVENT_ZONE_SOFT_APB:						return "SOFT_APB";
	}

	return "";
}

string BS2EventStringUtil::getSubEventStringEntranceLimitZone(uint16_t subEvent)
{
	switch (subEvent)
	{
	case BS2_SUB_EVENT_DEVICE_ZONE_HARD_ENTRANCE_LIMIT_COUNT:	return "HARD_ENTRANCE_LIMIT_COUNT";
	case BS2_SUB_EVENT_DEVICE_ZONE_SOFT_ENTRANCE_LIMIT_COUNT:	return "SOFT_ENTRANCE_LIMIT_COUNT";
	case BS2_SUB_EVENT_DEVICE_ZONE_HARD_ENTRANCE_LIMIT_TIME:	return "HARD_ENTRANCE_LIMIT_TIME";
	case BS2_SUB_EVENT_DEVICE_ZONE_SOFT_ENTRANCE_LIMIT_TIME:	return "SOFT_ENTRANCE_LIMIT_TIME";
	}

	return "";
}

string BS2EventStringUtil::getSubEventStringInterlockZone(uint16_t subEvent)
{
	switch (subEvent)
	{
	case BS2_SUB_EVENT_INTERLOCKZONE_DOOR_OPEN:				return "DOOR_OPEN";
	case BS2_SUB_EVENT_INTERLOCK_INPUT_DETECT:				return "INPUT_DETECT";
	}

	return "";
}

string BS2EventStringUtil::getSubEventStringAuthLimitZone(uint16_t subEvent)
{
	switch (subEvent)
	{
	case BS2_SUB_EVENT_ZONE_HARD_AUTH_LIMIT:				return "HARD_AUTH_LIMIT";
	case BS2_SUB_EVENT_ZONE_SOFT_AUTH_LIMIT:				return "SOFT_AUTH_LIMIT";
	case BS2_SUB_EVENT_ZONE_SCHEDULE_AUTH_LIMIT:			return "SCHEDULE_AUTH_LIMIT";
	case BS2_SUB_EVENT_ZONE_COUNT_AUTH_LIMIT:				return "COUNT_AUTH_LIMIT";
	case BS2_SUB_EVENT_ZONE_USER_AUTH_LIMIT:				return "USER_AUTH_LIMIT";
	}

	return "";
}

string BS2EventStringUtil::getSubEventStringDeviceIO(uint16_t subEvent)
{
	//switch (subEvent)
	//{
	////case BS2_SUB_EVENT_DEVICE_IO_INPUT_ON:					return "INPUT_ON";
	////case BS2_SUB_EVENT_DEVICE_IO_INPUT_OFF:					return "INPUT_OFF";
	////case BS2_SUB_EVENT_DEVICE_IO_OUTPUT_ON:					return "OUTPUT_ON";
	////case BS2_SUB_EVENT_DEVICE_IO_OUTPUT_OFF:				return "OUTPUT_OFF";
	//}

	return "";
}